# GNU Guix makefile
#
# To build faster_lmm_d on GNU Guix:
#
#   make -f Makefile.guix
#
# run with
#
#   ./build/faster_lmm_d

# The following two are modified by the Guix package:
D_COMPILER=ldc2
LDC_LIB_PATH=$(HOME)/.guix-profile/lib

DFLAGS = -wi -I. -IBioD -IundeaD/src
DLIBS  = $(LDC_LIB_PATH)/libphobos2-ldc.a $(LDC_LIB_PATH)/libdruntime-ldc.a
DLIBS_DEBUG = $(LDC_LIB_PATH)/libphobos2-ldc-debug.a $(LDC_LIB_PATH)/libdruntime-ldc-debug.a
RPATH  = -L--rpath=$(dir $(realpath $(LDC_LIB_PATH)/libz.so)):$(dir $(realpath $(LDC_LIB_PATH)/liblz4.so))
LIBS   = htslib/libhts.a -L-L$(LDC_LIB_PATH) -L-lrt -L-lpthread -L-lm -L-lz -L-llz4
SRC    = $(wildcard main.d source/*.d)
OBJ    = $(SRC:.d=.o)
OUT    = build/faster_lmm_d

# The Guix targets resolve the RPATH automatically
guix:        DFLAGS += -O -g -inline

guix-debug:  DFLAGS += -O0 -g -d-debug

# The development options are run from ~/.guix-profile and need to inject the RPATH
debug:       DFLAGS += -O0 -g -d-debug $(RPATH) -link-debuglib

release:     DFLAGS += -O -release -inline -noboundscheck $(RPATH)

profile:     DFLAGS += -g -O -profile $(RPATH)

guix release:             LIBS += $(DLIBS)

guix-debug debug profile: LIBS += $(DLIBS_DEBUG)

.PHONY: all guix guix-debug debug release profile clean test

all: debug

build-setup:
	mkdir -p build/

guix guix-debug default debug release profile: $(OUT)

# ---- Compile step
%.o: %.d
	$(D_COMPILER) $(DFLAGS) -c $< -od=$(dir $@)

# ---- Link step
$(OUT): build-setup $(OBJ)
	$(D_COMPILER) $(DFLAGS) -of=build/faster_lmm_d $(OBJ) $(LIBS)

test:
	./.run_tests.sh

debug-strip: debug
	objcopy --only-keep-debug build/sambamba sambamba.debug
	objcopy --strip-debug build/sambamba
	objcopy --add-gnu-debuglink=sambamba.debug build/sambamba
	mv sambamba.debug build/

install:
	install -m 0755 build/sambamba $(prefix)/bin

clean: clean-d
	cd htslib ; make clean

clean-d:
	rm -rf build/*
	rm -f $(OBJ) $(OUT) trace.{def,log}
